#if !canImport(ObjectiveC)
    import XCTest

    extension QueryStringEncoderTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__QueryStringEncoderTests = [
            ("testEncodes", testEncodes),
        ]
    }

    extension UtilsTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__UtilsTests = [
            ("testCamelToSnake", testCamelToSnake),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        [
            testCase(QueryStringEncoderTests.__allTests__QueryStringEncoderTests),
            testCase(UtilsTests.__allTests__UtilsTests),
        ]
    }
#endif
